services:

  web:
    image: satthuno99/core-fe:latest
    container_name: core-web
    restart: always
    networks:
      - core-network

  nginx:
    image: nginx:alpine
    container_name: core-nginx
    ports:
      - "80:80"
    volumes:
      - ../nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - core-network

networks:
  core-network:
    external: true
