services:

  web:
    image: satthuno99/core-fe:latest
    container_name: core-web
    restart: always
    expose:
      - "3000"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
    networks:
      - core-network

  nginx:
    image: nginx:alpine
    container_name: core-nginx
    restart: always
    environment:
      - VIRTUAL_HOST=cici21chualang.vn,www.cici21chualang.vn,ql-quy-pickleball.online,www.ql-quy-pickleball.online
      - LETSENCRYPT_HOST=cici21chualang.vn,www.cici21chualang.vn,ql-quy-pickleball.online,www.ql-quy-pickleball.online
      - LETSENCRYPT_EMAIL=core@cici21chualang.vn
    volumes:
      - ../docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    networks:
      - core-network

networks:
  core-network:
    external: true
