events {}

http {

    # Disable access log to prevent disk filling up
    access_log off;
    # Only log warnings and errors
    error_log /var/log/nginx/error.log warn;

    upstream web {
        server core-web:3000;
    }

    upstream api {
        server core-api:5000;
    }
    server {

        listen 80;
        server_name cici21chualang.vn www.cici21chualang.vn;

        location /api/ {
            proxy_pass http://api/;
            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location / {
            proxy_pass http://web;
            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    server {
        listen 80;
        server_name ql-quy-pickleball.online www.ql-quy-pickleball.online;

        location / {
          proxy_pass http://172.17.0.1:8501;
          proxy_http_version 1.1;
      
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
      }
    }
    
    server {
        listen 80;
        server_name openclaw-gateway.cici21chualang.vn www.openclaw-gateway.cici21chualang.vn;

        location / {
            proxy_pass http://172.17.0.1:18789;
            proxy_http_version 1.1;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
    server {
        listen 80;
        server_name ninerouter.cici21chualang.vn www.ninerouter.cici21chualang.vn;
    
        location / {
            proxy_pass http://172.17.0.1:20128;
            proxy_http_version 1.1;
    
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
    
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
    
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
    
            proxy_read_timeout 300;
        }
    }
}
