events {}

http {

    upstream web {
        least_conn;
        server core-web-1:3000;
        server core-web-2:3000;
    }

    upstream api {
        least_conn;
        server core-api-1:5000;
        server core-api-2:5000;
    }

    server {

        listen 80;

        location /api/ {
            proxy_pass http://api/;
        }

        location / {
            proxy_pass http://web;
        }

    }

}